name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  group: QA-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ubuntu-mpi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and upgrade dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mpich cmake

      - name: Build
        run: ENABLE_MPI=true bash configure.sh
      
      - name: Run
        run: mpirun -np 2 bin/Release/mpidemo

      - name: Test 1 cores
        run: mpirun -np 1 ./bin/Release/test
      
      - name: Test 2 cores
        run: mpirun -np 2 ./bin/Release/test

      - name: Test 4 cores
        run: mpirun -np 4 ./bin/Release/test
      
      - name: Test 8 cores
        run: mpirun -np 8 ./bin/Release/test
      

  ubuntu-single-thread:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and upgrade dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Build
        run: bash configure.sh

      - name: Run
        run: bin/Release/mpidemo

      - name: Test
        run: ./bin/Release/test

  windows-single-thread:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        run: .\configure.bat
      
      - name: Run
        run: .\bin\Release\mpidemo.exe
  
      - name: Test
        run: .\bin\Release\test.exe