name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  group: QA-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ubuntu-mpi:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: 'true'

      - name: Install and upgrade dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ mpich libtbb-dev

      - name: Build
        run: MPI_ENABLED=true bash configure.sh

      - name: Test 1 cores
        run: |
          rm -rf tmp/ &> /dev/null
          mpirun -np 1 bin/Release/test

      - name: Test 2 cores
        run: |
          rm -rf tmp/ &> /dev/null
          mpirun -np 2 bin/Release/test

      - name: Test 4 cores
        run: |
          rm -rf tmp/ &> /dev/null
          mpirun -np 4 bin/Release/test
      
      - name: Test 8 cores
        run: |
          rm -rf tmp/ &> /dev/null
          mpirun -np 8 bin/Release/test


  ubuntu-single-thread:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: 'true'

      - name: Install and upgrade dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libtbb-dev

      - name: Build
        run: bash configure.sh

      - name: Test
        run: ./bin/Release/test

  windows-single-thread:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: 'true'

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        run: .\configure.bat

      - name: Test
        run: .\bin\Release\test.exe
